# Generated by Django 5.2.8 on 2025-12-30 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseallocation",
            name="lecturer",
            field=models.ForeignKey(
                limit_choices_to={"is_lecturer": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_allocations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
