# Generated by Django 5.2.7 on 2025-11-20 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_newsandevents_summary_en_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="semester",
            name="session",
        ),
        migrations.AddField(
            model_name="newsandevents",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_superuser": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="news_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="semester",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_superuser": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="semesters",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Session",
        ),
    ]
