# Generated by Django 5.2.7 on 2025-12-25 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_semester_session_newsandevents_admin_and_more"),
        ("course", "0008_course_admin_courseallocation_admin_program_admin_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(unique=True)),
                ("is_current", models.BooleanField(default=False)),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_superuser": True},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_academic_years",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[("First", "First"), ("Second", "Second")],
                        max_length=10,
                    ),
                ),
                ("is_current", models.BooleanField(default=False)),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_superuser": True},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_modules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Module",
                "verbose_name_plural": "Modules",
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_ru", models.CharField(max_length=200)),
                ("name_en", models.CharField(max_length=200)),
                ("name_kg", models.CharField(max_length=200)),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_superuser": True},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_programs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Program",
                "verbose_name_plural": "Programs",
            },
        ),
        migrations.DeleteModel(
            name="ActivityLog",
        ),
        migrations.AlterModelOptions(
            name="semester",
            options={"verbose_name": "Semester", "verbose_name_plural": "Semesters"},
        ),
        migrations.RemoveField(
            model_name="semester",
            name="is_current_semester",
        ),
        migrations.RemoveField(
            model_name="semester",
            name="next_semester_begins",
        ),
        migrations.RemoveField(
            model_name="semester",
            name="semester",
        ),
        migrations.AddField(
            model_name="semester",
            name="courses",
            field=models.ManyToManyField(related_name="semesters", to="course.course"),
        ),
        migrations.AddField(
            model_name="semester",
            name="is_current",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="semester",
            name="name",
            field=models.CharField(
                choices=[("First", "First"), ("Second", "Second")],
                default="First",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="semester",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_superuser": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_semesters",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="semester",
            name="academic_year",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="semesters",
                to="core.academicyear",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="module",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modules",
                to="core.semester",
            ),
        ),
        migrations.AddField(
            model_name="academicyear",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_years",
                to="core.program",
            ),
        ),
        migrations.DeleteModel(
            name="NewsAndEvents",
        ),
    ]
