# Generated by Django 4.2.28 on 2026-02-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_alter_course_code_alter_course_credit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="html_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
