# Generated by Django 4.0.8 on 2026-02-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_code_alter_course_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner - New to FlutterFlow'), ('Intermediate', 'Intermediate - Building Apps'), ('Advanced', 'Advanced - Professional Builder')], max_length=25),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('First', 'Phase 1 - Foundations'), ('Second', 'Phase 2 - Building'), ('Third', 'Phase 3 - Launch')], max_length=200),
        ),
    ]
