# Generated by Django 5.2.7 on 2025-10-21 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_group_student_group"),
        ("course", "0004_alter_course_code_alter_course_credit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseallocation",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.group",
            ),
        ),
    ]
