# Generated by Django 4.2.28 on 2026-03-01 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0005_upload_html_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="level",
        ),
    ]
