# Generated by Django 5.2.7 on 2025-10-24 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_newsandevents_summary_es_newsandevents_summary_fr_and_more"),
        ("course", "0005_courseallocation_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courseallocation",
            name="session",
        ),
        migrations.AddField(
            model_name="courseallocation",
            name="semester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.semester",
            ),
        ),
    ]
