# Generated by Django 4.0.8 on 2026-03-04 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cohort_and_more'),
        ('course', '0005_alter_course_level_alter_course_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseallocation',
            name='session',
            field=models.ForeignKey(blank=True, db_column='session_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.programcycle'),
        ),
    ]
