# Generated by Django 4.0.8 on 2026-09-09 14:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0005_scormpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadvideo',
            name='video_type',
            field=models.CharField(choices=[('file', 'Uploaded Video'), ('youtube', 'YouTube Video')], default='file', max_length=20),
        ),
        migrations.AddField(
            model_name='uploadvideo',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Paste the YouTube video URL', null=True),
        ),
        migrations.AlterField(
            model_name='uploadvideo',
            name='video',
            field=models.FileField(blank=True, help_text='Valid video formats: mp4, mkv, wmv, 3gp, f4v, avi, mp3', null=True, upload_to='course_videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mkv', 'wmv', '3gp', 'f4v', 'avi', 'mp3'])]),
        ),
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_seconds', models.FloatField(default=0)),
                ('duration_seconds', models.FloatField(default=0)),
                ('progress_percent', models.FloatField(default=0)),
                ('last_position', models.FloatField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='course.uploadvideo')),
            ],
            options={
                'unique_together': {('student', 'video')},
            },
        ),
    ]
