# Generated by Django 5.2.7 on 2025-11-20 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0007_remove_course_summary_en_remove_course_summary_es_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_superuser": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="courseallocation",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_superuser": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_course_allocations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_superuser": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_programs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="upload",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_superuser": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_uploads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="uploadvideo",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_superuser": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_upload_videos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
