# Generated by Django 5.2.7 on 2025-12-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_departmenthead_department_and_more"),
        ("course", "0008_course_admin_courseallocation_admin_program_admin_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program",
            name="admin",
        ),
        migrations.RemoveField(
            model_name="course",
            name="program",
        ),
        migrations.RemoveField(
            model_name="upload",
            name="admin",
        ),
        migrations.RemoveField(
            model_name="upload",
            name="course",
        ),
        migrations.RemoveField(
            model_name="uploadvideo",
            name="admin",
        ),
        migrations.RemoveField(
            model_name="uploadvideo",
            name="course",
        ),
        migrations.RemoveField(
            model_name="course",
            name="code",
        ),
        migrations.RemoveField(
            model_name="course",
            name="credit",
        ),
        migrations.RemoveField(
            model_name="course",
            name="is_elective",
        ),
        migrations.RemoveField(
            model_name="course",
            name="level",
        ),
        migrations.RemoveField(
            model_name="course",
            name="semester",
        ),
        migrations.RemoveField(
            model_name="course",
            name="summary",
        ),
        migrations.RemoveField(
            model_name="course",
            name="year",
        ),
        migrations.AddField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name="CourseOffer",
        ),
        migrations.DeleteModel(
            name="Program",
        ),
        migrations.DeleteModel(
            name="Upload",
        ),
        migrations.DeleteModel(
            name="UploadVideo",
        ),
    ]
