# Generated by Django 4.2.16 on 2024-10-04 22:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_alter_course_code_alter_course_credit_and_more"),
        ("quiz", "0003_choice_choice_es_choice_choice_fr_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="essayquestion",
            options={
                "verbose_name": "Essay Style Question",
                "verbose_name_plural": "Essay Style Questions",
            },
        ),
        migrations.RenameField(
            model_name="choice",
            old_name="choice",
            new_name="choice_text",
        ),
        migrations.RenameField(
            model_name="choice",
            old_name="choice_en",
            new_name="choice_text_en",
        ),
        migrations.RenameField(
            model_name="choice",
            old_name="choice_es",
            new_name="choice_text_es",
        ),
        migrations.RenameField(
            model_name="choice",
            old_name="choice_fr",
            new_name="choice_text_fr",
        ),
        migrations.RenameField(
            model_name="choice",
            old_name="choice_ru",
            new_name="choice_text_ru",
        ),
        migrations.AlterField(
            model_name="mcquestion",
            name="choice_order",
            field=models.CharField(
                blank=True,
                choices=[
                    ("content", "Content"),
                    ("random", "Random"),
                    ("none", "None"),
                ],
                default="random",
                help_text="The order in which multiple-choice options are displayed to the user",
                max_length=30,
                verbose_name="Choice Order",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="question",
            name="figure",
            field=models.ImageField(
                blank=True,
                default="test",
                help_text="Add an image for the question if necessary.",
                upload_to="uploads/%Y/%m/%d",
                verbose_name="Figure",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="quiz",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("assignment", "Assignment"),
                    ("exam", "Exam"),
                    ("practice", "Practice Quiz"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="course.course",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="quiz",
            name="draft",
            field=models.BooleanField(
                default=False,
                help_text="If yes, the quiz is not displayed in the quiz list and can only be taken by users who can edit quizzes.",
                verbose_name="Draft",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="pass_mark",
            field=models.SmallIntegerField(
                default=50,
                help_text="Percentage required to pass exam.",
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="Pass Mark",
            ),
        ),
        migrations.AlterField(
            model_name="sitting",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="course.course",
                verbose_name="Course",
            ),
            preserve_default=False,
        ),
    ]
