# Generated by Django 4.0.8 on 2026-02-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner - New to FlutterFlow'), ('Intermediate', 'Intermediate - Building Apps'), ('Advanced', 'Advanced - Professional Builder')], max_length=25, null=True),
        ),
    ]
