# Generated by Django 5.2.7 on 2025-11-20 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_group_student_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="departmenthead",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_superuser": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_department_heads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_superuser": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_superuser": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_students",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
