# Generated by Django 5.2.7 on 2025-12-25 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_departmenthead_admin_group_admin_student_admin"),
        ("core", "0006_academicyear_module_program_delete_activitylog_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departmenthead",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.program",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="program",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.program",
            ),
        ),
    ]
