# Generated by Django 4.2.28 on 2026-03-01 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0006_remove_course_level"),
        ("ai_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chunk_index",
                    models.IntegerField(
                        help_text="Zero-based position of this chunk within the document."
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Plain text content of this chunk."),
                ),
                (
                    "embedding",
                    models.JSONField(
                        blank=True,
                        help_text="Embedding vector as a JSON list of floats.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="course.upload",
                    ),
                ),
            ],
            options={
                "ordering": ["upload", "chunk_index"],
                "unique_together": {("upload", "chunk_index")},
            },
        ),
    ]
