# Generated by Django 5.2.7 on 2025-11-20 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_superuser": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_attendances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="scheduleitem",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_superuser": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_schedule_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
