# Generated by Django 4.2.20 on 2025-12-29 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scheduleitem",
            name="end",
        ),
        migrations.RemoveField(
            model_name="scheduleitem",
            name="order",
        ),
        migrations.RemoveField(
            model_name="scheduleitem",
            name="start",
        ),
    ]
