# Generated by Django 5.2.7 on 2025-11-20 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_attendance_admin_scheduleitem_admin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scheduleitem",
            options={
                "ordering": ["date", "lesson_time__order"],
                "verbose_name": "Schedule Item",
                "verbose_name_plural": "Schedule Items",
            },
        ),
        migrations.AddField(
            model_name="scheduleitem",
            name="date",
            field=models.DateField(
                blank=True, help_text="Дата проведения урока", null=True
            ),
        ),
        migrations.AlterField(
            model_name="scheduleitem",
            name="end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="scheduleitem",
            name="order",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="scheduleitem",
            name="start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="LessonTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        help_text="Номер урока (1, 2, 3, ...)", unique=True
                    ),
                ),
                ("start_time", models.TimeField(help_text="Время начала урока")),
                ("end_time", models.TimeField(help_text="Время окончания урока")),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        help_text="Администратор, создавший это расписание времен",
                        limit_choices_to={"is_superuser": True},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_times",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lesson Time",
                "verbose_name_plural": "Lesson Times",
                "ordering": ["order"],
                "unique_together": {("order", "admin")},
            },
        ),
        migrations.AddField(
            model_name="scheduleitem",
            name="lesson_time",
            field=models.ForeignKey(
                blank=True,
                help_text="Время урока (автоматически определяет start и end)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="attendance.lessontime",
            ),
        ),
    ]
